# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='n/a', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='resource',
            field=models.FileField(upload_to='board_media'),
        ),
    ]
