# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnexForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('details', jsonfield.fields.JSONField(blank=True, default=None, help_text='Example: [{type: Site, color: #12345}]', null=True)),
            ],
        ),
    ]
