# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    replaces = [('forms', '0001_initial'), ('forms', '0002_turnexform_publish'), ('forms', '0003_turnexform_order'), ('forms', '0004_auto_20170618_0357'), ('forms', '0005_auto_20170624_1747'), ('forms', '0006_turnextype'), ('forms', '0007_auto_20170923_2119')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnexForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('details', jsonfield.fields.JSONField(blank=True, default=None, help_text='Example: [{type: Site, color: #12345}]', null=True)),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TurnexType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('form_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='forms.TurnexForm')),
            ],
        ),
    ]
