# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_squashed_0007_auto_20170923_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnextype',
            name='description',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnexform',
            name='order',
            field=models.IntegerField(),
        ),
    ]
