# Generated by Django 2.2.27 on 2022-03-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20170923_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnextype',
            name='form_owner',
            field=models.ForeignKey(on_delete=None, related_name='types', to='forms.TurnexForm'),
        ),
    ]
