# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_turnexform_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnexform',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
