# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_turnexform_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnexform',
            old_name='publish',
            new_name='published',
        ),
    ]
