# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20170618_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnexform',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='turnexform',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
